### ISSUE TITLE
Customizable root indicators

### ISSUE THREAD

**Issue by thatch** [python-packaging/tuber#1]
Given a subdirectory of e.g. a git repo, the `get_root` function will tell you the root of that repo.  Pretty straightforward goal, and there are some tests already.

For this issue,
1. Modify [`get_root`](https://github.com/python-packaging/tuber/blob/main/tuber/__init__.py#L20) to take an iterable ([`typing.Iterable[str]`](https://docs.python.org/3/library/typing.html#typing.Iterable)) of indicators.  Using this type, list, set, and tuple should all work.
2. Default to the current `ROOT_INDICATORS`
3. Add a test that shows the customization works
4. Submit a PR!

Quick development instructions

1. `git clone clone https://github.com/python-packaging/tuber`
2. `cd tuber`
3. `make venv`
4. `source .venv/bin/activate`
5. `make test` (runs unittest)

Make sure the code is formatted (`make format`) and types are good (`make lint`) before submitting a PR to save iteration time waiting on CI.

**Comment by spencerkee** [comment]
Hi @thatch, could you assign the issue to me?

**Comment by thatch** [comment]
Let me know if there's anything I can help with on this one as well.
