### ISSUE TITLE
Implementing `walk`

### ISSUE THREAD

**Issue by thatch** [python-packaging/tuber#2]
An additional function that would be really helpful to have here would be a generator function that calls [`os.walk`](https://docs.python.org/3/library/os.html#os.walk) on a path, apply includes/excludes, and yields the resulting paths.

Something like

```
tuber.walk(root: Path, includes: Iterable[str]=("*.py",), excludes: Iterable[str]=(".git", "*.ext.py"))
```

For this issue

1. Implement `walk` using an API similar to the above
2. Bonus points for defaulting `excludes` to the same as [black uses](https://github.com/psf/black/blob/master/src/black/__init__.py#L68)
4. Make sure there's a test
5. Submit a PR!

Quick development instructions

1. `git clone clone https://github.com/python-packaging/tuber`
2. `cd tuber`
3. `make venv`
4. `source .venv/bin/activate`
5. `make test` (runs unittest)

Make sure the code is formatted (`make format`) and types are good (`make lint`) before submitting a PR to save iteration time waiting on CI.

**Comment by spencerkee** [comment]
Hi @thatch, could you assign the issue to me? I can get started shortly.

**Comment by thatch** [comment]
Spencer, let me know if you're stuck on part of this and I can try to find more docs or snippets that would help

**Comment by spencerkee** [comment]
Hi @thatch, took me a bit of time to get setup on a new computer. https://github.com/python-packaging/tuber/pull/3 for your review.
